### ISSUE TITLE
Source for Awesome.Data.Sql.Builder.OData?

### ISSUE THREAD

**Issue by gabriel-alecu** [cdroulers/awesome-sql-builder#13]
Hello!

This is not exactly a code issue, more like a project one.

You mentioned Awesome.Data.Sql.Builder.OData, and the nuget package for it links to this repo, but I don't see the source for it anywhere.
Is it not public for some reason, or is it just hard to find?

**Comment by cdroulers** [comment]
Hey!

I migrated to .NET core recently and the packages for OData were not the same / available or something. I simply deleted the project from the master branch.

It's still available in older versions here: https://github.com/cdroulers/awesome-sql-builder/tree/4b68c2df811ac6dda281943787a823c3e53c1ac6 and if it's useful to you, you could create a fork from that and modify it at will and I'll gladly merge it back for reguler .NET deployment!
